name = "lapce-typescript"
version = "0.0.1"
author = "panekj"
display-name = "Typescript / Javascript"
description = "TS/JS for Lapce: powered by typescript-language-server"
wasm = "bin/lapce-typescript.wasm"
